# Create a conda environment using this file by running:
# conda env create -f environment.yaml
name: migdar-data-pipelines
channels:
  - defaults
dependencies:
  - ipython>=7.0.1
  - jupyter>=1.0.0
  - jupyterlab>=0.35.0
  - leveldb>=1.20
  - python=3.6
  - psycopg2
  - pip:
    - plyvel
    - datapackage-pipelines-elasticsearch
    - https://github.com/OriHoch/dataflows/archive/specify-encoding-for-load.zip#egg=dataflows[speedup]
    - https://github.com/frictionlessdata/datapackage-pipelines/archive/2.0.0.zip#egg=datapackage-pipelines[speedup]
